/*
 * generated by Xtext 2.25.0
 */
package com.github.johasarelvdberg.sofl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSoflDslScopeProvider extends DelegatingScopeProvider {
}
